---
title: "sepsis_eda_cleaning"
output: html_document
date: "2023-01-30"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(ggplot2)
library(forcats)
library(tidyr)
library(NbClust)
library(reshape2) 
```

```{r}
df_clean = read.csv(file = "./vitals_trajectory_cleaned.csv")
```


```{r}
tmp = df_clean %>%
  group_by(EncID) %>% 
  filter(row_number()==1) 

summary(tmp$died_hour_round)

nrow(tmp %>%
       filter(died_hour_round <=12))/
  nrow(tmp %>%
         filter(!is.na(died_hour_round)))

ggplot(tmp, aes(x=died_hour_round)) + 
  geom_histogram(binwidth=1) +
  ggtitle('Hour from Admission to Death (MODS=1 on Day1 Patients)')+
  theme_bw()

ggplot(tmp, aes(x=died_hour_round)) + 
  geom_histogram(binwidth=1) +
  xlim(0,168) +
  ggtitle('Hour to Death 7-Day Zoom in')+
  geom_vline(xintercept = 12, color='blue') +
  theme_bw()

```


```{r}
age_sum = tmp %>%
  group_by(age_group) %>%
  summarise(n = n())%>%
  mutate (order = c(1,3,6,2,4,5)) %>%
  ungroup()%>%
  arrange(order)

ggplot(data=age_sum, aes(x=fct_reorder(age_group, order), y=n)) +
  geom_bar(stat="identity") +
  xlab('age_group') +
  ylab('count')+
  ggtitle('Patient in Each Age Group')+
  theme_bw()

age_sum2 = gather(tmp %>%
  group_by(age_group) %>%
  summarise(mods_day7 = sum(mods_day7)/n(),
            died_in_hosp = sum(died_in_hosp)/n())%>%
  mutate (order = c(1,3,6,2,4,5)) %>%
  ungroup()%>%
  arrange(order), key = 'count_type', value = 'value',2:3)

ggplot(data=age_sum2, aes(x=fct_reorder(age_group, order), y=value, fill=count_type)) +
  geom_bar(stat="identity", position=position_dodge()) +
  xlab('age_group') +
  ylab('proportion of age group')+
  ggtitle('Ratio of Death in Hospital and MODS Day7 per Age Group')+
  theme_bw()

age_died_time = gather(tmp %>%
  group_by(age_group) %>%
  summarise(died_time_mean = mean(died_hour_round,na.rm=TRUE),
            died_time_median = median(died_hour_round,na.rm=TRUE))  %>%
  mutate (order = c(1,3,6,2,4,5)) %>%
  ungroup()%>%
  arrange(order), key = 'statistic', value = 'value',2:3)

ggplot(data=age_died_time, aes(x=fct_reorder(age_group, order), y=value, group=statistic)) +
  geom_line(aes(color=statistic))+
  geom_point(aes(color=statistic))+
  xlab('age_group') +
  ylab('hour')+
  ggtitle('Death Time from Admission (Hr) by Age Group')+
  theme_bw()

```
```{r}
hosp_sum = gather(tmp %>%
  group_by(hospital_id) %>%
  summarise(mods_day7 = sum(mods_day7)/n(),
            died_in_hosp = sum(died_in_hosp)/n()),
  key = 'count_type', value = 'value',2:3)

ggplot(data=hosp_sum, aes(x=hospital_id, y=value, fill=count_type)) +
  geom_bar(stat="identity", position=position_dodge()) +
  xlab('hospital id') +
  ylab('proportion of hospital patients')+
  ggtitle('Ratio of Death in Hospital and MODS Day7 per Hospital')+
  theme_bw()

```

```{r}
per_hr_count = df_clean %>%
  filter(!is.na(event_value)) %>%
  group_by(event_name, event_hour) %>%
  summarize(n = n_distinct(EncID)) 

alive_hr = df_clean %>%
  mutate(died_hour_whole = round(died_hour_round)) %>%
  filter(!is.na(died_hour_round)) %>%
  select(EncID, died_hour_round) %>%
  distinct() %>%
  filter(died_hour_round <13) %>%
  mutate(died_hour = floor(died_hour_round)) %>%
  group_by(died_hour) %>%
  summarize(n = n()) %>%
  ungroup()%>%
  mutate(sum = cumsum(n)) %>%
  mutate(alive = 12842-sum, event_name='Alive') %>%
  select(event_name, died_hour, alive) %>%
  rename("n" = "alive", 'event_hour' = 'died_hour') 
  
per_hr = rbind(per_hr_count, alive_hr)

ggplot(data=per_hr, aes(x=event_hour, y=n, group=event_name)) +
  geom_line(aes(color=event_name))+
  geom_point(aes(color=event_name))+
  xlab('event_hr') +
  ylab('number of patients')+
  ggtitle('Number of Patients per Event per Hour')+
  theme_bw()
```

```{r}
ggplot(df_clean, aes(x=as.factor(event_hour), y=event_value_norm)) + 
  geom_boxplot(outlier.size=1) +
  facet_wrap(~event_name, scales = "free") +
  xlab('Hour from Admission') +
  ylab('Vitals Value Normalized by Age') +
  ggtitle('Vitals Trajectory Normalized by Age Group') +
  theme_bw()

ggplot(df_clean, aes(x=as.factor(event_hour), y=event_value)) + 
  geom_boxplot(outlier.size=1) +
  facet_wrap(~event_name, scales = "free") +
  xlab('Hour from Admission') +
  ylab('Vitals Value') +
  ggtitle('Vitals Trajectory') +
  theme_bw()
```

```{r}
df_clus = read.csv(file = './vitals_trajectory_cluster_label_2cluster.csv')
```

```{r}
head(df_clus)
```

```{r}
cluster_sum_orig = df_clus %>%
  group_by(cluster_label_orig, event_hour ) %>%
  summarize (temp_mean = mean(TEMPImputed,na.rm=TRUE), 
             sf_ratio_mean = mean(SF_RATIOImputed,na.rm=TRUE), 
             sbp_mean = mean(SBPImputed,na.rm=TRUE), 
             resp_mean = mean(RESP_RATEImputed,na.rm=TRUE), 
             pulse_mean = mean(PULSEImputed,na.rm=TRUE),
             map_mean = mean(MAPImputed,na.rm=TRUE),
             )
cluster_sum_melt_orig <- melt(cluster_sum_orig, id = c("cluster_label_orig","event_hour"))

cluster_sum_v2 = df_clus %>%
  group_by(cluster_label_v2, event_hour ) %>%
  summarize (temp_mean = mean(TEMPImputed,na.rm=TRUE), 
             sf_ratio_mean = mean(SF_RATIOImputed,na.rm=TRUE), 
             sbp_mean = mean(SBPImputed,na.rm=TRUE), 
             resp_mean = mean(RESP_RATEImputed,na.rm=TRUE), 
             pulse_mean = mean(PULSEImputed,na.rm=TRUE),
             map_mean = mean(MAPImputed,na.rm=TRUE),
             )
cluster_sum_melt_v2 <- melt(cluster_sum_v2, id = c("cluster_label_v2","event_hour"))

cluster_sum_pen2 = df_clus %>%
  group_by(cluster_label_pen2, event_hour ) %>%
  summarize (temp_mean = mean(TEMPImputed,na.rm=TRUE), 
             sf_ratio_mean = mean(SF_RATIOImputed,na.rm=TRUE), 
             sbp_mean = mean(SBPImputed,na.rm=TRUE), 
             resp_mean = mean(RESP_RATEImputed,na.rm=TRUE), 
             pulse_mean = mean(PULSEImputed,na.rm=TRUE),
             map_mean = mean(MAPImputed,na.rm=TRUE),
             )
cluster_sum_melt_pen2 <- melt(cluster_sum_pen2, id = c("cluster_label_pen2","event_hour"))


ggplot(data=cluster_sum_melt_orig, aes(x=event_hour, y=value, group=as.factor(cluster_label_orig))) +
  geom_line(aes(color=as.factor(cluster_label_orig)))+
  geom_point(aes(color=as.factor(cluster_label_orig)))+
  xlab('Event Hour') +
  ylab('Mean Measurement Value (Normalized)')+
  ggtitle('Original Mean Measurement Value over Time by Cluster')+
  theme_bw() +
  facet_wrap(~variable) +
  xlim(0,13)

ggplot(data=cluster_sum_melt_v2, aes(x=event_hour, y=value, group=as.factor(cluster_label_v2))) +
  geom_line(aes(color=as.factor(cluster_label_v2)))+
  geom_point(aes(color=as.factor(cluster_label_v2)))+
  xlab('Event Hour') +
  ylab('Mean Measurement Value (Normalized)')+
  ggtitle('New Data Pen5 Mean Measurement Value over Time by Cluster')+
  theme_bw() +
  facet_wrap(~variable) +
  xlim(0,13)


ggplot(data=cluster_sum_melt_pen2, aes(x=event_hour, y=value, group=as.factor(cluster_label_pen2))) +
  geom_line(aes(color=as.factor(cluster_label_pen2)))+
  geom_point(aes(color=as.factor(cluster_label_pen2)))+
  xlab('Event Hour') +
  ylab('Mean Measurement Value (Normalized)')+
  ggtitle('New Data Pen2 Mean Measurement Value over Time by Cluster')+
  theme_bw() +
  facet_wrap(~variable) +
  xlim(0,13)
```

```{r}
cluster_outcome_orig = df_clus %>%
  group_by(EncID) %>%
  filter(row_number()==1) %>%
  ungroup() %>%
  group_by(cluster_label_orig) %>%
  summarize (mods_day7_mean = sum(mods_day7)/n(), 
             died_in_hosp_mean = sum(died_in_hosp)/n()
             )
cluster_outcome_melt_orig <- melt(cluster_outcome_orig, id = "cluster_label_orig")

cluster_outcome_v2 = df_clus %>%
  group_by(EncID) %>%
  filter(row_number()==1) %>%
  ungroup() %>%
  group_by(cluster_label_v2) %>%
  summarize (mods_day7_mean = sum(mods_day7)/n(), 
             died_in_hosp_mean = sum(died_in_hosp)/n()
             )
cluster_outcome_melt_v2 <- melt(cluster_outcome_v2, id = "cluster_label_v2")

cluster_outcome_pen2 = df_clus %>%
  group_by(EncID) %>%
  filter(row_number()==1) %>%
  ungroup() %>%
  group_by(cluster_label_pen2) %>%
  summarize (mods_day7_mean = sum(mods_day7)/n(), 
             died_in_hosp_mean = sum(died_in_hosp)/n()
             )
cluster_outcome_melt_pen2 <- melt(cluster_outcome_pen2, id = "cluster_label_pen2")

ggplot(data=cluster_outcome_melt_orig, aes(x=variable, y=value, fill=as.factor(cluster_label_orig))) +
  geom_bar(stat="identity", color="black", position=position_dodge())+
  xlab('Outcome') +
  ylab('Percentage within Cluster')+
  ggtitle('Original Outcome by Cluster')+
  theme_bw()

ggplot(data=cluster_outcome_melt_v2, aes(x=variable, y=value, fill=as.factor(cluster_label_v2))) +
  geom_bar(stat="identity", color="black", position=position_dodge())+
  xlab('Outcome') +
  ylab('Percentage within Cluster')+
  ggtitle('New Data Pen5 Outcome by Cluster')+
  theme_bw()

ggplot(data=cluster_outcome_melt_pen2, aes(x=variable, y=value, fill=as.factor(cluster_label_pen2))) +
  geom_bar(stat="identity", color="black", position=position_dodge())+
  xlab('Outcome') +
  ylab('Percentage within Cluster')+
  ggtitle('New Data Pen2 Outcome by Cluster')+
  theme_bw()
```


  
```{r}
# age group distribution
cluster_age2= df_clus %>%
  group_by(EncID) %>%
  filter(row_number()==1) %>% 
  ungroup() %>%
  group_by(cluster_label) %>%
  mutate(cluster_sum = n())%>%
  group_by(age_group, add=TRUE) %>%
  mutate(per=round(n()/cluster_sum,2)) %>%
  select(age_group, cluster_label, per) %>%
  distinct() %>%
  arrange(age_group, cluster_label)%>%
  ungroup()%>%
  mutate(order = c(1,1,3,3,6,6,2,2,4,4,5,5))


ggplot(cluster_age2, aes(fill=fct_reorder(age_group, order), y=per, x=cluster_label)) + 
  geom_bar(position="fill", stat="identity") +
  ylab('Percentage within Cluster')+
  xlab('Cluster') +
  ggtitle('Cluster Age Distribution')+
  theme_bw() 
```

```{r}
death_time_cluster = df_clus %>%
  select(EncID, died_hour_round,cluster_label) %>%
  distinct() %>%
  drop_na() %>%
  arrange(died_hour_round) %>%
  mutate(idx = row_number())

 ggplot(death_time_cluster, aes(x=as.factor(cluster_label), y=died_hour_round, fill=as.factor(cluster_label))) + 
  geom_violin() +
  geom_boxplot(width=0.1, alpha=0.7) +
  xlab('Cluster') +
  ylab('Recorded Death Time') +
  ylim(0,1440) +
  ggtitle('Death Time by Cluster (within 60 days)') +
  theme_bw()
```

```{r}
labs = read.csv('./vitals_labs_cluster.csv')
labs
```

```{r}

interv_orig = labs %>%
  select(cluster_label_orig, malignancy, transplant, vent, crrt, ecmo, vaso_drug)  %>%
  group_by(cluster_label_orig) %>%
  summarize (vent_mean = sum(vent)/n(),
             crrt_mean = sum(crrt)/n(),
             ecmo_mean = sum(ecmo)/n(),
             vaso_mean = sum(vaso_drug)/n()
             )
cluster_interv_melt_orig <- melt(interv_orig , id = "cluster_label_orig")

interv_v2 = labs %>%
  select(cluster_label_v2, malignancy, transplant, vent, crrt, ecmo, vaso_drug)  %>%
  group_by(cluster_label_v2) %>%
  summarize (vent_mean = sum(vent)/n(),
             crrt_mean = sum(crrt)/n(),
             ecmo_mean = sum(ecmo)/n(),
             vaso_mean = sum(vaso_drug)/n()
             )
cluster_interv_melt_v2 <- melt(interv_v2 , id = "cluster_label_v2")

interv_pen2 = labs %>%
  select(cluster_label_pen2, malignancy, transplant, vent, crrt, ecmo, vaso_drug)  %>%
  group_by(cluster_label_pen2) %>%
  summarize (vent_mean = sum(vent)/n(),
             crrt_mean = sum(crrt)/n(),
             ecmo_mean = sum(ecmo)/n(),
             vaso_mean = sum(vaso_drug)/n()
             )
cluster_interv_melt_pen2 <- melt(interv_pen2 , id = "cluster_label_pen2")

ggplot(data=cluster_interv_melt_orig, aes(x=variable, y=value, fill=as.factor(cluster_label_orig))) +
  geom_bar(stat="identity", color="black", position=position_dodge())+
  xlab('Intervention') +
  ylab('Percentage within Cluster')+
  ggtitle('Original Intervention by Cluster')+
  theme_bw()

ggplot(data=cluster_interv_melt_v2, aes(x=variable, y=value, fill=as.factor(cluster_label_v2))) +
  geom_bar(stat="identity", color="black", position=position_dodge())+
  xlab('Intervention') +
  ylab('Percentage within Cluster')+
  ggtitle('New Data Pen5 Intervention by Cluster')+
  theme_bw()


ggplot(data=cluster_interv_melt_pen2, aes(x=variable, y=value, fill=as.factor(cluster_label_pen2))) +
  geom_bar(stat="identity", color="black", position=position_dodge())+
  xlab('Intervention') +
  ylab('Percentage within Cluster')+
  ggtitle('New Data Pen2 Intervention by Cluster')+
  theme_bw()

```
```{r}

```